theme: jekyll-theme-minimal

title: Derek Lilienthal
logo: /assets/img/Fonoti.Photography-1855.jpg
description: AI Researcher, Machine Learning Enthusiast, M.S. in Artificial Intelligence  

Linkedin:
  https://www.linkedin.com/in/derek-lilienthal/
